
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javafx.scene.input.KeyCode.O;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class conexionupdate extends javax.swing.JFrame {

    /**
     * Creates new form conexionupdate
     */
    Connection con;
    Statement stmt,st;
    int num_reg,cant_reg;
    String myquery1="", myquery2="", myquery3="";
    ResultSet rs1,rs2, rs3;
    public conexionupdate() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btsave = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        txcode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cbgene = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txdire = new javax.swing.JTextField();
        txtele = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txcodigo = new javax.swing.JTextField();
        btbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbcelda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txregis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txde = new javax.swing.JTextField();
        btnext = new javax.swing.JButton();
        btfinal = new javax.swing.JButton();
        btanterior = new javax.swing.JButton();
        btinicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btsave.setBackground(new java.awt.Color(153, 0, 153));
        btsave.setText("save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btcancelar.setText("cancelar");

        btexit.setText("salir");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos"));

        jLabel5.setText("Genero");

        jLabel6.setText("Email");

        jLabel4.setText("Direccion");

        jLabel3.setText("Telefono");

        jLabel2.setText("Nombre");

        jLabel9.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15)
                                .addComponent(txname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtele, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbgene, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txdire, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txdire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbgene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btbuscar.setText("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Criterio");

        cbcelda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AlumnoCode", "AlumnoName", "AlumnoTel", "AlumnoDir", "AlumnoEmail", "AlumnoGene" }));
        cbcelda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbceldaActionPerformed(evt);
            }
        });

        jLabel7.setText("Registro");

        txregis.setEditable(false);
        txregis.setEnabled(false);

        jLabel8.setText("De");

        txde.setEditable(false);
        txde.setEnabled(false);

        btnext.setText(">");
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        btfinal.setText(">>");
        btfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfinalActionPerformed(evt);
            }
        });

        btanterior.setText("<");
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });

        btinicio.setText("<<");
        btinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btfinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbcelda, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txcode, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txregis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txde, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btsave)
                        .addGap(18, 18, 18)
                        .addComponent(btcancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btexit)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbuscar)
                    .addComponent(jLabel1)
                    .addComponent(cbcelda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txregis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btfinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btanterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btinicio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsave)
                    .addComponent(btcancelar)
                    .addComponent(btexit))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public  void limpiar(){
        txcode.setText("");
        txcodigo.setText("");
        txname.setText("");
        txtele.setText("");
        txdire.setText("");
        txemail.setText("");
}
 
    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        String myquery = "";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/matricula","root","");
            stmt = con.createStatement();
            System.out.println("Conexión exitosa a la base de datos");
            myquery = "UPDATE Alumno SET AlumnoName = '" + txname.getText() + "', AlumnoTel = '" + txtele.getText() + "', AlumnoDir = '" + txdire.getText() + "', AlumnoEmail = '" + txemail.getText() + "', AlumnoGene = '" + cbgene.getSelectedItem() + "' WHERE AlumnoCode = '" + txcode.getText() + "'";
            int rowsAffected = stmt.executeUpdate(myquery);
            System.out.println(rowsAffected + " fila(s) actualizada(s) correctamente");
            con.close();
        } catch (SQLException e) {
            System.err.println("Error al conectar a la base de datos: " + e.getMessage());
        }
        limpiar();
    }//GEN-LAST:event_btsaveActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        // TODO add your handling code here:
        
        num_reg=1;
        cant_reg=1;
        try{
            myquery1="select count(*) as cantidad from alumno where "+cbcelda.getSelectedItem() +"='"+txcode.getText()+"'";
            myquery2="select * from alumno where "+cbcelda.getSelectedItem()+"='"+txcode.getText()+"'";
            rs1 = st.executeQuery(myquery1);
            rs1.next();
            cant_reg=Integer.parseInt(rs1.getString("cantidad"));
            txregis.setText(""+num_reg);
            txde.setText(""+cant_reg);
            rs1.close();
            rs2=st.executeQuery(myquery2);
            rs2.next();
            txcodigo.setText(""+rs2.getInt("AlumnoCode"));
            txname.setText(rs2.getString("AlumnoName"));
            txtele.setText(rs2.getString("AlumnoTel"));
            txdire.setText(rs2.getString("AlumnoDir"));
            txemail.setText(rs2.getString("AlumnoEmail"));
            cbgene.addItem(rs2.getString("AlumnoGene"));
        }catch (Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btbuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/matricula","root","");
            st=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            
            
        }catch (Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        try{
        if(num_reg==cant_reg)
               JOptionPane.showMessageDialog(null, "No hay mas registros");
        else{
             cbgene.removeAllItems();
            num_reg++;
            txregis.setText(""+num_reg);
            rs2.next();
                txcodigo.setText(""+rs2.getInt("AlumnoCode"));
                txname.setText(rs2.getString("AlumnoName"));
                txtele.setText(rs2.getString("AlumnoTel"));
                txdire.setText(rs2.getString("AlumnoDir"));
                txemail.setText(rs2.getString("AlumnoEmail"));
                cbgene.addItem(rs2.getString("AlumnoGene"));

        }
        
        }catch (Exception e){
        
        }
    }//GEN-LAST:event_btnextActionPerformed

    private void btfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfinalActionPerformed
        // TODO add your handling code here:
        try{
        if(num_reg==cant_reg)
               JOptionPane.showMessageDialog(null, "No hay mas registros");
        else{
            cbgene.removeAllItems();
            num_reg=cant_reg;
            txregis.setText(""+num_reg);
            rs2.last();
                txcodigo.setText(""+rs2.getInt("AlumnoCode"));
                txname.setText(rs2.getString("AlumnoName"));
                txtele.setText(rs2.getString("AlumnoTel"));
                txdire.setText(rs2.getString("AlumnoDir"));
                txemail.setText(rs2.getString("AlumnoEmail"));
                cbgene.addItem(rs2.getString("AlumnoGene"));
        }
        }catch (Exception e){
        
        }
    }//GEN-LAST:event_btfinalActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed
        // TODO add your handling code here:
        try{
        if(num_reg==1)
               JOptionPane.showMessageDialog(null, "No hay mas registros");
        else{
            cbgene.removeAllItems();
            num_reg=num_reg-1;
            txregis.setText(""+num_reg);
            rs2.previous();
                txcodigo.setText(""+rs2.getInt("AlumnoCode"));
                txname.setText(rs2.getString("AlumnoName"));
                txtele.setText(rs2.getString("AlumnoTel"));
                txdire.setText(rs2.getString("AlumnoDir"));
                txemail.setText(rs2.getString("AlumnoEmail"));
                cbgene.addItem(rs2.getString("AlumnoGene"));
        }
        }catch (Exception e){
        
        }
    }//GEN-LAST:event_btanteriorActionPerformed

    private void btinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinicioActionPerformed
        // TODO add your handling code here:
        try{
        if(num_reg==1)
               JOptionPane.showMessageDialog(null, "No hay mas registros");
        else{
            cbgene.removeAllItems();
            num_reg=1;
            txregis.setText(""+num_reg);
            rs2.first();
                txcodigo.setText(""+rs2.getInt("AlumnoCode"));
                txname.setText(rs2.getString("AlumnoName"));
                txtele.setText(rs2.getString("AlumnoTel"));
                txdire.setText(rs2.getString("AlumnoDir"));
                txemail.setText(rs2.getString("AlumnoEmail"));
                cbgene.addItem(rs2.getString("AlumnoGene"));
        }
        }catch (Exception e){
        
        }
    }//GEN-LAST:event_btinicioActionPerformed

    private void cbceldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbceldaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbceldaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conexionupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conexionupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conexionupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conexionupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conexionupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btanterior;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btfinal;
    private javax.swing.JButton btinicio;
    private javax.swing.JButton btnext;
    private javax.swing.JButton btsave;
    private javax.swing.JComboBox<String> cbcelda;
    private javax.swing.JComboBox<String> cbgene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txcode;
    private javax.swing.JTextField txcodigo;
    private javax.swing.JTextField txde;
    private javax.swing.JTextField txdire;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txname;
    private javax.swing.JTextField txregis;
    private javax.swing.JTextField txtele;
    // End of variables declaration//GEN-END:variables
}
