/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabajos_clases;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class trabajo extends javax.swing.JFrame {

    /**
     * Creates new form trabajo
     */
    public trabajo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bsuma = new javax.swing.JButton();
        txnum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txnum2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRes = new javax.swing.JLabel();
        bresta = new javax.swing.JButton();
        bdivi = new javax.swing.JButton();
        bmul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("caluladoras");

        bsuma.setText("suma");
        bsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsumaActionPerformed(evt);
            }
        });

        jLabel2.setText("Num1");

        jLabel3.setText("Num2");

        txnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnum2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Repuesta es:");

        bresta.setText("resta");
        bresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brestaActionPerformed(evt);
            }
        });

        bdivi.setText("dividir");
        bdivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiviActionPerformed(evt);
            }
        });

        bmul.setText("multiplicar");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bdivi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bmul))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bsuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bresta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txnum1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsuma)
                    .addComponent(bresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdivi)
                    .addComponent(bmul))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsumaActionPerformed
        // TODO add your handling code here:
        String num1, num2;
        int n1,n2,suma = 0;
        num1 = txnum1.getText();
        num2 = txnum2.getText();
        if(num1.isEmpty() || num2.isEmpty())
            JOptionPane.showMessageDialog(null, "no se puede hacer");
        else{
                n1 = Integer.parseInt(num1);
                n2 = Integer.parseInt(num2);
                suma = n1+n2;
                }
        jRes.setText("" + suma);

    }//GEN-LAST:event_bsumaActionPerformed

    private void brestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brestaActionPerformed
        // TODO add your handling code here:
        String num1, num2;
        int n1,n2,suma = 0;
        num1 = txnum1.getText();
        num2 = txnum2.getText();
        if(num1.isEmpty() || num2.isEmpty())
            JOptionPane.showMessageDialog(null, "no se puede hacer");
        else{
                n1 = Integer.parseInt(num1);
                n2 = Integer.parseInt(num2);
                suma = n1-n2;
                }
        jRes.setText("" + suma);
    }//GEN-LAST:event_brestaActionPerformed

    private void bdiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiviActionPerformed
        // TODO add your handling code here:
        int num1 = Integer.parseInt(txnum1.getText());
        int num2 = Integer.parseInt(txnum2.getText());
        if (num2 != 0) {
            // Realizar la división
            double division = (double) num1 / num2;

            // Mostrar el resultado en la etiqueta correspondiente
            jRes.setText("" + division);
        } else {
            jRes.setText("No se puede dividir entre cero");
        }
    }//GEN-LAST:event_bdiviActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        // TODO add your handling code here:
        String num1, num2;
        int n1,n2,suma = 0;
        num1 = txnum1.getText();
        num2 = txnum2.getText();
        if(num1.isEmpty() || num2.isEmpty())
            JOptionPane.showMessageDialog(null, "no se puede hacer");
        else{
                n1 = Integer.parseInt(num1);
                n2 = Integer.parseInt(num2);
                suma = n1*n2;
                }
        jRes.setText("" + suma);
    }//GEN-LAST:event_bmulActionPerformed

    private void txnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnum2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdivi;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bresta;
    private javax.swing.JButton bsuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jRes;
    private javax.swing.JTextField txnum1;
    private javax.swing.JTextField txnum2;
    // End of variables declaration//GEN-END:variables
}
