
import static com.sun.deploy.uitoolkit.impl.fx.ui.MixedCodeInSwing.show;
import static java.lang.Integer.toString;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
    import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class factura extends javax.swing.JFrame {

    static void recibirDatosProducto(String codigo, String descripcion, String precio, String cantidad) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    Connection con,connection;
    Statement stmt,st;
    
    /** Creates new form factura */
    public factura() {
        initComponents();
        
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txdes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txpre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txcant = new javax.swing.JTextField();
        Btagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfactucode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproducto = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txfecha = new javax.swing.JTextField();
        btsalir = new javax.swing.JButton();
        Btquitar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txcliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfecha1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txsubt = new javax.swing.JTextField();
        txisv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnuevo = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btmonstar = new javax.swing.JButton();
        btguardar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto"));
        jPanel1.setToolTipText("");

        jLabel2.setText("Codigo");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Precio");

        jLabel5.setText("Cantidad");

        Btagregar.setText("Agregar");
        Btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btagregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txcant, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txcode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txpre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txdes, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btagregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Codigo");

        txfactucode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfactucodeActionPerformed(evt);
            }
        });

        tbproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Cantidad", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbproducto);
        if (tbproducto.getColumnModel().getColumnCount() > 0) {
            tbproducto.getColumnModel().getColumn(0).setResizable(false);
            tbproducto.getColumnModel().getColumn(1).setResizable(false);
            tbproducto.getColumnModel().getColumn(2).setResizable(false);
            tbproducto.getColumnModel().getColumn(3).setResizable(false);
            tbproducto.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setText("Fecha");

        txfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfechaActionPerformed(evt);
            }
        });

        btsalir.setBackground(new java.awt.Color(255, 51, 51));
        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        Btquitar.setText("quitar");
        Btquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtquitarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cliente");

        jLabel8.setText("Vendedor");

        txfecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfecha1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Sub-Total");

        txsubt.setText("0");

        txisv.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("I.S.V");

        txtotal.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Total");

        btnuevo.setBackground(new java.awt.Color(0, 255, 0));
        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btcancelar.setBackground(new java.awt.Color(255, 153, 0));
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btguardar.setBackground(new java.awt.Color(204, 0, 204));
        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });

        btmonstar.setText("mostar");
        btmonstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmonstarActionPerformed(evt);
            }
        });

        btguardar1.setBackground(new java.awt.Color(204, 0, 204));
        btguardar1.setText("GuardarD");
        btguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btcancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btguardar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(txcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(txfactucode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(10, 10, 10)
                                                .addComponent(txsubt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(10, 10, 10)
                                                .addComponent(txisv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(10, 10, 10)
                                                .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btmonstar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Btquitar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfactucode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btmonstar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btquitar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txsubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsalir)
                            .addComponent(btnuevo)
                            .addComponent(btcancelar)
                            .addComponent(btguardar)
                            .addComponent(btguardar1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txisv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel11)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     public void recibirDatosProducto(String codigo, String descripcion, String precio, String cantidad) {
        txtCodigo.setText(codigo);
        txtDescripcion.setText(descripcion);
        txtPrecio.setText(precio);
        txtCantidad.setText(cantidad);
    }
    public void guardafactura(){
        String myquery1 = "";
try {
    con = DriverManager.getConnection("jdbc:mysql://localhost/facturacion","root","");
             stmt = con.createStatement();
            System.out.println("Conexión exitosa a la base de datos");
    myquery1 = "INSERT INTO factura (facturaID, facturaDate, CilenteID, VendedorID, facturasubt, facturaISV, facturaTotal) VALUES ('" + txfactucode.getText() + "', '" + txfecha.getText() + "', '" + txcliente.getText() + "', '" + txcliente.getText() + "', '" + txsubt.getText() + "', '" + txisv.getText() + "', '" + txtotal.getText() + "')";
    int rowsAffected = stmt.executeUpdate(myquery1);
    System.out.println(rowsAffected + " fila(s) insertada(s) correctamente");

    con.close();
} catch (SQLException e) {
    System.err.println("Error al conectar a la base de datos: " + e.getMessage());
}
    }


private void calcularSubtotal() {
    DefaultTableModel mymodelo = (DefaultTableModel) tbproducto.getModel();
    int columnaSubtotal = 4;
    double subtotal = 0.0;
    double isvPorcentaje = 0.15;

    for (int i = 0; i < mymodelo.getRowCount(); i++) {
        double valorSubtotal = Double.parseDouble(mymodelo.getValueAt(i, columnaSubtotal).toString());
        subtotal += valorSubtotal;
    }

    double isv = subtotal * isvPorcentaje;
    isv = Math.round(isv * 100.0) / 100.0; // Redondea a 2 decimales

    txsubt.setText(String.valueOf(subtotal));

    DecimalFormatSymbols symbols = new DecimalFormatSymbols();
    symbols.setDecimalSeparator('.'); // Establece el punto como separador decimal
    DecimalFormat df = new DecimalFormat("#0.00", symbols); // Formato personalizado

    txisv.setText(df.format(isv));

    double totalGeneral = subtotal + isv;
    txtotal.setText(String.valueOf(totalGeneral));
}



private void guardarDatosDetalleFactura() {
    try {
        String facturaID = txfactucode.getText(); // Obtener el valor de FacturaID del JTextField
        connection = DriverManager.getConnection("jdbc:mysql://localhost/facturacion","root","");
        String sql = "INSERT INTO detallefactura (FacturaID, ProductoID, Precio, detalleCantidad, detallesubt) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement statement = connection.prepareStatement(sql);

        DefaultTableModel model = (DefaultTableModel) tbproducto.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            String productoID = model.getValueAt(i, 0).toString();
            String descripcion = model.getValueAt(i, 1).toString();
            String precio = model.getValueAt(i, 2).toString();
            String cantidad = model.getValueAt(i, 3).toString();
            String subtotal = model.getValueAt(i, 4).toString();

            statement.setString(1, facturaID);
            statement.setString(2, productoID);
            statement.setString(3, precio);
            statement.setString(4, cantidad);
            statement.setString(5, subtotal);

            statement.executeUpdate();
        }

        statement.close();
        connection.close();

        System.out.println("Datos insertados correctamente en la tabla detallefactura");
    } catch (SQLException e) {
        System.err.println("Error al insertar datos en la tabla detallefactura: " + e.getMessage());
    }
}
public void mostar(){
    int indice = tbproducto.getSelectedRow();
        if (indice >= 0) {
        DefaultTableModel mymodelo = (DefaultTableModel) tbproducto.getModel();
        Object[] filaSeleccionada = new Object[mymodelo.getColumnCount()];
        
        for (int i = 0; i < mymodelo.getColumnCount(); i++) {
            filaSeleccionada[i] = mymodelo.getValueAt(indice, i);
        }
        
        String mensaje = "Fila seleccionada: ";
        for (Object valor : filaSeleccionada) {
            mensaje += valor.toString() + " ";
        }
        JOptionPane.showMessageDialog(null, mensaje);
        }
}

    private void txfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfechaActionPerformed

    private void BtagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtagregarActionPerformed
        // TODO add your handling code here:
        double subt = Integer.parseInt(txpre.getText()) * Integer.parseInt(txcant.getText());
        String subto= " "+subt; 
        String[] datos = {txcode.getText(), txdes.getText(),txpre.getText(),txcant.getText(), subto};
        DefaultTableModel mymodelo = (DefaultTableModel) tbproducto.getModel();
        mymodelo.addRow(datos);
        txcode.setText("");
        txdes.setText("");
        txpre.setText("");
        txcant.setText("");
        
        calcularSubtotal();
    }//GEN-LAST:event_BtagregarActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsalirActionPerformed

    private void BtquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtquitarActionPerformed
        // TODO add your handling code here:
        int indice = tbproducto.getSelectedRow();
        if (indice >= 0) {
        DefaultTableModel mymodelo = (DefaultTableModel) tbproducto.getModel();
        mymodelo.removeRow(indice);
        }
        calcularSubtotal();
    }//GEN-LAST:event_BtquitarActionPerformed

    private void txfecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfecha1ActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        // TODO add your handling code here:
        guardafactura();
        guardarDatosDetalleFactura();

    }//GEN-LAST:event_btguardarActionPerformed

    private void btmonstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmonstarActionPerformed
        // TODO add your handling code here:
       mostar();
    }//GEN-LAST:event_btmonstarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         String url = "jdbc:mysql://localhost/facturacion";
        String username = "root";
        String password = "";

        try {
            Connection con = DriverManager.getConnection(url, username, password);
            System.out.println("Conexión exitosa a la base de datos");
            // Aquí puedes realizar operaciones con la conexión establecida
            con.close();
        } catch (SQLException e) {
            System.err.println("Error al conectar a la base de datos: " + e.getMessage());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardar1ActionPerformed
        // TODO add your handling code here:
        guardarDatosDetalleFactura();
    }//GEN-LAST:event_btguardar1ActionPerformed

    private void txfactucodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfactucodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfactucodeActionPerformed

    private void tbproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductoMouseClicked
        // TODO add your handling code here:
        mostar();
    }//GEN-LAST:event_tbproductoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        productos pro = new productos();
pro.setVisible(true); // Asegurarse de que el JFrame sea visible para poder verlo

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btagregar;
    private javax.swing.JButton Btquitar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btguardar1;
    private javax.swing.JButton btmonstar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbproducto;
    private javax.swing.JTextField txcant;
    private javax.swing.JTextField txcliente;
    private javax.swing.JTextField txcode;
    private javax.swing.JTextField txdes;
    private javax.swing.JTextField txfactucode;
    private javax.swing.JTextField txfecha;
    private javax.swing.JTextField txfecha1;
    private javax.swing.JTextField txisv;
    private javax.swing.JTextField txpre;
    private javax.swing.JTextField txsubt;
    private javax.swing.JTextField txtotal;
    // End of variables declaration//GEN-END:variables

}
