
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pc
 */
public class productos extends javax.swing.JFrame {
    private factura factura;

    /**
     * Creates new form productos
     */
    public productos() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tx_buscar = new javax.swing.JTextField();
        bt_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("productos");

        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "description", "precio", "cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbproductos);

        jLabel2.setText("Buscar");

        tx_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_buscarKeyPressed(evt);
            }
        });

        bt_ok.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(tx_buscar)))
                    .addComponent(bt_ok))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_ok)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 // Variable para guardar la referencia al formulario de factura

    public void setFactura(factura factura) {
        this.factura = factura;
    }
    public void enviarDatosAFactura(String codigo, String descripcion, String precio, String cantidad) {
        if (factura != null) {
            factura.recibirDatosProducto(codigo, descripcion, precio, cantidad);
        }
    }
public void seleccionarFila() {
        int indiceFilaSeleccionada = tbproductos.getSelectedRow();

        if (indiceFilaSeleccionada >= 0) {
            DefaultTableModel modeloTabla = (DefaultTableModel) tbproductos.getModel();
            String codigo = modeloTabla.getValueAt(indiceFilaSeleccionada, 0).toString();
            String descripcion = modeloTabla.getValueAt(indiceFilaSeleccionada, 1).toString();
            String precio = modeloTabla.getValueAt(indiceFilaSeleccionada, 2).toString();
            String cantidad = modeloTabla.getValueAt(indiceFilaSeleccionada, 3).toString();

            // Enviar los datos al formulario de factura
            enviarDatosAFactura(codigo, descripcion, precio, cantidad);
        }
    }


    public void llenarTabla() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/facturacion", "root", "");
            Statement stmt = con.createStatement();

            // Ejecutar la consulta y obtener los resultados en un objeto ResultSet
            String query = "SELECT * FROM productos";
            ResultSet resultSet = stmt.executeQuery(query);

            // Obtener el modelo de tabla
            DefaultTableModel model = (DefaultTableModel) tbproductos.getModel();

            // Limpiar la tabla antes de llenarla con nuevos datos
            model.setRowCount(0);

            // Iterar sobre los resultados del ResultSet y agregar cada fila al modelo de la tabla
            while (resultSet.next()) {
                Object[] row = new Object[4];
                row[0] = resultSet.getInt("codigo");
                row[1] = resultSet.getString("description");
                row[2] = resultSet.getString("precio");
                row[3] = resultSet.getString("cantidad");
                model.addRow(row);
            }
            // Cerrar la conexión y el Statement

            stmt.close();
            con.close();
        } catch (SQLException e) {
            System.err.println("Error al conectar a la base de datos: " + e.getMessage());
        }
    }
    private void tbproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductosMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tbproductosMouseClicked

    private void tx_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_buscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_buscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbproductos;
    private javax.swing.JTextField tx_buscar;
    // End of variables declaration//GEN-END:variables
}
